version: "3"
services:
  strapi:
    build: .
    ports:
      - 1337:1337
    volumes:
      - ./:/opt/app
    depends_on:
      db:
        condition: service_healthy
  db:
    platform: linux/x86_64
    image: mysql:8
    ports:
      - 3306:3306
    restart: always
    command: --authentication_policy=mysql_native_password
    volumes:
      - ~/Strapi/accounts/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
      MYSQL_ROOT_PASSWORD: strapi
      MYSQL_ROOT_HOST: "%"
    healthcheck:
      test: mysqladmin --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD ping
      timeout: 5s
      retries: 5
